services:
  webserver:
    image: nginx:1.26.1-alpine-slim
    container_name: nginx
    depends_on:
      - drupal
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./drupal-data:/opt/drupal
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - external
  postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRESPASS}
      - POSTGRES_USER=${POSTGRESUSER}
      - POSTGRES_DB=${POSTGRESDB}
  
  drupal:
    image: drupal:${DRUPALIMAGE}
    container_name: drupal
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - internal
      - external
    volumes:
      - ./drupal-data/web:/var/www/html

networks:
  external:
    driver: bridge
  internal:
    driver: bridge